version: "3"
services:
  newsservice:
    container_name: newsservice
    restart: always
    build: ./server/   
    ports:
      - '5000:5000'
    links:
      - mongo
  mongo:
    container_name: mongo
    restart: always
    image: mongo
    ports:
      - "27017:27017"
  reactclient:
    container_name: reactclient
    restart: always
    build: ./client/
    ports:
      - '3000:3000'